---
sudo: required
os: osx
language: generic
osx_image: xcode11.2 # macOS 10.14

install:
  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo mkdir -p /etc/ansible
  - "{ echo -e '[localhost]'; echo 'local ansible_connection=local'; } | sudo tee /etc/ansible/hosts"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook main.yaml --syntax-check"

  # Test the playbook.
  - "travis_wait 30 ansible-playbook -vv main.yaml"

  # Test the playbook's idempotence.
  - idempotence=$(mktemp)
  - "ansible-playbook main.yaml -vv | tee -a ${idempotence}"
  - >
    tail ${idempotence}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
...
