---
sudo: required
os: osx
language: generic
osx_image: xcode11.2 # macOS 10.14

install:
  # Install Ansible
  - sudo pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

  # Add a hosts file.
  - sudo mkdir -p /etc/ansible
  - "{ echo -e '[localhost]'; echo 'local ansible_connection=local'; } | sudo tee /etc/ansible/hosts"

  # Update Homebrew
  - brew update

env:
  - ANSIBLE_SKIP='--skip-tags mas'
  - ANSIBLE_PLAYBOOK=main.yaml
  - ANSIBLE_COMMAND="ansible-playbook -vv ${ANSIBLE_SKIP} {ANSIBLE_PLAYBOOK}"

script:
  # Check the role/playbook's syntax.
  - "ansible-playbook ${ANSIBLE_PLAYBOOK} --syntax-check"

  # Test the playbook.
  - "travis_wait 30 ${ANSIBLE_COMMAND}

  # Test the playbook's idempotence.
  - idempotence_test_log=$(mktemp)
  - "${ANSIBLE_COMMAND} | tee -a ${idempotence_test_log}"
  - >
    tail ${idempotence_test_log}
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
...
