---
- name: Configure macOS
  hosts: localhost
  vars:
    update_dotfiles: true
    dotfiles_repo: pegasd/dotfiles
    brew_packages:
      - pwgen
      - pssh
      - vim
      - mercurial
      - cvs
      - grep # GNU Grep is nice
      - jq
      - python
      - kubectl
      - most
    brew_present_casks:
      - intellij-idea
      - slack
      - transmission
      - java
      - dash
      - google-chrome
      - istat-menus
      - iterm2
      - 1password6
      - google-cloud-sdk
      - pdk
      - docker
    brew_absent_casks:
      - jetbrains-toolbox
    update_vim_plugins: false
    vim_plugins:
      - name: syntastic
        repo: vim-syntastic/syntastic
      - name: tabular
        repo: godlygeek/tabular
  tasks:
    - include: tasks/osx_defaults.yaml
      tags: [ osx_defaults ]
    - include: tasks/applications.yaml
      tags: [ applications ]
    - include: tasks/dotfiles.yaml
      tags: [ applications, dotfiles ]
...
