---
- name: Configure macOS
  hosts: localhost
  vars:
    mas_signin_dialog: no
    update_dotfiles: true
    dotfiles_repo: https://gitlab.com/the_pegas/dotfiles
    mas_installed_apps:
      - { name: Magnet, id: 441258766 }
      - { name: Spark, id: 1176895641 }
      - { name: Telegram, id: 747648890 }
      - { name: Xcode, id: 497799835 }
      - { name: Xee, id: 639764244 }
    brew_present_taps:
      - homebrew/cask
      - homebrew/cask-versions
      - puppetlabs/puppet
    brew_absent_taps: []
    brew_present_packages:
      - awscli
      - byobu
      - colordiff
      - cfssl
      - cvs
      - git-flow
      - gnupg
      - grep # GNU Grep is nice
      - htop
      - jq
      - kubectl
      - kubernetes-cli
      - mercurial
      - pinentry-mac
      - pssh
      - pwgen
      - python
      - terraform
      - travis
      - unar
      - vim
      - yq
    brew_absent_packages:
      - most
      - multitail
      - unrar
    brew_present_casks:
      - 1password
      - dash
      - docker
      - drawio
      - firefox
      - google-chrome
      - google-cloud-sdk
      - intellij-idea
      - istat-menus
      - iterm2
      - java
      - openemu
      - pdk
      - puppet-agent
      - skype
      - slack
      - transmission
      - visual-studio-code
      - vlc
    brew_absent_casks:
      - jetbrains-toolbox
    fonts:
      - font-ubuntumono-nerd-font-mono
    update_vim_plugins: false
    vim_plugins:
      - name: syntastic
        repo: https://github.com/vim-syntastic/syntastic
      - name: tabular
        repo: https://github.com/godlygeek/tabular
  tasks:
    - include: tasks/osx_defaults.yaml
      tags: [ osx_defaults ]
    - include: tasks/iterm.yaml
      tags: [ osx_defaults, iterm ]
    - include: tasks/applications.yaml
      tags: [ applications ]
    - include: tasks/mas.yaml
      tags: [ applications, mas ]
    - include: tasks/dotfiles.yaml
      tags: [ applications, dotfiles ]
    - include: tasks/fonts.yaml
      tags: [ fonts ]
...
