---
- name: Configure macOS
  hosts: localhost
  vars:
    update_dotfiles: true
    dotfiles_repo: https://gitlab.com/the_pegas/dotfiles
    brew_present_packages:
      - awscli
      - byobu
      - colordiff
      - cvs
      - grep # GNU Grep is nice
      - htop
      - jq
      - kubectl
      - kubernetes-cli
      - mercurial
      - most
      - pssh
      - pwgen
      - python
      - travis
      - vim
    brew_absent_packages:
      - multitail
    brew_present_casks:
      - dash
      - docker
      - firefox
      - google-chrome
      - google-cloud-sdk
      - intellij-idea
      - istat-menus
      - iterm2
      - java
      - pdk
      - skype
      - slack
      - transmission
      - vlc
      - xee
    brew_absent_casks:
      - jetbrains-toolbox
    fonts:
      - font-ubuntumono-nerd-font-mono
    update_vim_plugins: false
    vim_plugins:
      - name: syntastic
        repo: https://github.com/vim-syntastic/syntastic
      - name: tabular
        repo: https://github.com/godlygeek/tabular
  tasks:
    - include: tasks/osx_defaults.yaml
      tags: [ osx_defaults ]
    - include: tasks/iterm.yaml
      tags: [ osx_defaults, iterm ]
    - include: tasks/applications.yaml
      tags: [ applications ]
    - include: tasks/dotfiles.yaml
      tags: [ applications, dotfiles ]
    - include: tasks/fonts.yaml
      tags: [ fonts ]
...
