- name: brew cask
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: Ensure brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - mercurial
    - cvs
    - grep
    - jq
    - python

- name: Ensure brew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - jetbrains-toolbox
    - dash
    - google-chrome
    - istat-menus
    - iterm2
    - 1password6

# App Store
# - Slack
# - Spark
# - Magnet
# - Telegram
# - Xcode
# - TweetDeck
