---
#
# Packages
#
- name: Regular brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - mercurial
    - cvs
    - grep # GNU Grep is nice
    - jq
    - python
    - kubectl
    - most

#
# Casks
#
- name: Homebrew cask tap
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: PuppetLabs cask tap
  homebrew_tap:
    name: puppetlabs/puppet
    state: present

- name: Brew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - jetbrains-toolbox
    - java
    - dash
    - google-chrome
    - istat-menus
    - iterm2
    - 1password6
    - google-cloud-sdk
    - pdk
    - docker

#
# App Store
#
# - Slack
# - Spark
# - Magnet
# - Telegram
# - Xcode
# - TweetDeck
