#
# Packages
#
- name: Regular brew packages
  homebrew:
    name: "{{ item }}"
    state: present
  loop:
    - vim
    - mercurial
    - cvs
    - grep
    - jq
    - python
    - kubectl

#
# Casks
#
- name: Cask brew tap
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: Brew casks
  homebrew_cask:
    name: "{{ item }}"
    state: present
  loop:
    - jetbrains-toolbox
    - dash
    - google-chrome
    - istat-menus
    - iterm2
    - 1password6
    - google-cloud-sdk

#
# App Store
#
# - Slack
# - Spark
# - Magnet
# - Telegram
# - Xcode
# - TweetDeck
