---
#
# Packages
#
- name: Regular brew packages
  homebrew:
    name: '{{ item }}'
    state: present
  loop: '{{ brew_packages }}'

#
# Casks
#
- name: Homebrew cask tap
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: PuppetLabs cask tap
  homebrew_tap:
    name: puppetlabs/puppet
    state: present

- name: Brew casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
  loop: '{{ brew_cask_packages }}'

#
# App Store
#
# - Slack
# - Spark
# - Magnet
# - Telegram
# - Xcode
# - TweetDeck
