---
- name: Homebrew cask tap
  homebrew_tap:
    name: homebrew/cask
    state: present

- name: PuppetLabs cask tap
  homebrew_tap:
    name: puppetlabs/puppet
    state: present

- name: Brew absent casks
  homebrew_cask:
    name: '{{ item }}'
    state: absent
  loop: '{{ brew_absent_casks }}'

- name: Brew present casks
  homebrew_cask:
    name: '{{ item }}'
    state: present
  loop: '{{ brew_present_casks }}'
