---
- name: Bring over my dotfiles
  git:
    dest: '~/.dotfiles'
    repo: '{{ dotfiles_repo }}'
    update: '{{ update_dotfiles }}'
    force: '{{ update_dotfiles }}'

- name: rsync '~/.dotfiles' -> '~'
  synchronize:
    src: '~/.dotfiles/'
    dest: '~'
    archive: false
    recursive: true
    rsync_opts:
      - '--exclude=.git'
      - '--exclude=LICENSE'
      - '--exclude=*.md'

- name: Vim plugins
  git:
    dest: '~/.vim/bundle/{{ item.name }}'
    repo: '{{ item.repo }}'
    update: '{{ update_vim_plugins }}'
    force: '{{ update_vim_plugins }}'
  loop: '{{ vim_plugins }}'

- name: history directory
  file:
    path: ~/.history
    state: directory
    mode: 0700
